#:schema node_modules/wrangler/config-schema.json
name = "__change_me__"
main = "src/worker.tsx"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
assets = { binding = "ASSETS" }

[observability]
enabled = true

[durable_objects]
bindings = [
  { name = "SESSION_DURABLE_OBJECT", class_name = "SessionDurableObject" }
]

[vars]
SECRET_KEY = "_"
APP_NAME = "__change_me__"

[[migrations]]
tag = "v1"
new_classes = [ "SessionDurableObject" ]

[[d1_databases]]
binding = "DB"
database_name = "__change_me__"
database_id = "__change_me__"